name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Extract repository name
      run: |
        REPO_NAME="${{ github.repository }}"
        echo "REPO_NAME_ONLY='${REPO_NAME##*/}'" >> $GITHUB_ENV
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: |
          ${{ env.REPO_NAME_ONLY }}.3dsx
          ${{ env.REPO_NAME_ONLY }}.cia
